/*
Candlepin

Candlepin is a subscription management server written in Java. It helps with management of software subscriptions.

API version: 4.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package caliri

import (
	"encoding/json"
)

// checks if the CryptographicCapabilitiesDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CryptographicCapabilitiesDTO{}

// CryptographicCapabilitiesDTO Describes the cryptographic capabilities of a consumer or receiver of cryptographic assets
type CryptographicCapabilitiesDTO struct {
	KeyAlgorithms []string `json:"keyAlgorithms,omitempty"`
	SignatureAlgorithms []string `json:"signatureAlgorithms,omitempty"`
}

// NewCryptographicCapabilitiesDTO instantiates a new CryptographicCapabilitiesDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptographicCapabilitiesDTO() *CryptographicCapabilitiesDTO {
	this := CryptographicCapabilitiesDTO{}
	return &this
}

// NewCryptographicCapabilitiesDTOWithDefaults instantiates a new CryptographicCapabilitiesDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptographicCapabilitiesDTOWithDefaults() *CryptographicCapabilitiesDTO {
	this := CryptographicCapabilitiesDTO{}
	return &this
}

// GetKeyAlgorithms returns the KeyAlgorithms field value if set, zero value otherwise.
func (o *CryptographicCapabilitiesDTO) GetKeyAlgorithms() []string {
	if o == nil || IsNil(o.KeyAlgorithms) {
		var ret []string
		return ret
	}
	return o.KeyAlgorithms
}

// GetKeyAlgorithmsOk returns a tuple with the KeyAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptographicCapabilitiesDTO) GetKeyAlgorithmsOk() ([]string, bool) {
	if o == nil || IsNil(o.KeyAlgorithms) {
		return nil, false
	}
	return o.KeyAlgorithms, true
}

// HasKeyAlgorithms returns a boolean if a field has been set.
func (o *CryptographicCapabilitiesDTO) HasKeyAlgorithms() bool {
	if o != nil && !IsNil(o.KeyAlgorithms) {
		return true
	}

	return false
}

// SetKeyAlgorithms gets a reference to the given []string and assigns it to the KeyAlgorithms field.
func (o *CryptographicCapabilitiesDTO) SetKeyAlgorithms(v []string) {
	o.KeyAlgorithms = v
}

// GetSignatureAlgorithms returns the SignatureAlgorithms field value if set, zero value otherwise.
func (o *CryptographicCapabilitiesDTO) GetSignatureAlgorithms() []string {
	if o == nil || IsNil(o.SignatureAlgorithms) {
		var ret []string
		return ret
	}
	return o.SignatureAlgorithms
}

// GetSignatureAlgorithmsOk returns a tuple with the SignatureAlgorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptographicCapabilitiesDTO) GetSignatureAlgorithmsOk() ([]string, bool) {
	if o == nil || IsNil(o.SignatureAlgorithms) {
		return nil, false
	}
	return o.SignatureAlgorithms, true
}

// HasSignatureAlgorithms returns a boolean if a field has been set.
func (o *CryptographicCapabilitiesDTO) HasSignatureAlgorithms() bool {
	if o != nil && !IsNil(o.SignatureAlgorithms) {
		return true
	}

	return false
}

// SetSignatureAlgorithms gets a reference to the given []string and assigns it to the SignatureAlgorithms field.
func (o *CryptographicCapabilitiesDTO) SetSignatureAlgorithms(v []string) {
	o.SignatureAlgorithms = v
}

func (o CryptographicCapabilitiesDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CryptographicCapabilitiesDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyAlgorithms) {
		toSerialize["keyAlgorithms"] = o.KeyAlgorithms
	}
	if !IsNil(o.SignatureAlgorithms) {
		toSerialize["signatureAlgorithms"] = o.SignatureAlgorithms
	}
	return toSerialize, nil
}

type NullableCryptographicCapabilitiesDTO struct {
	value *CryptographicCapabilitiesDTO
	isSet bool
}

func (v NullableCryptographicCapabilitiesDTO) Get() *CryptographicCapabilitiesDTO {
	return v.value
}

func (v *NullableCryptographicCapabilitiesDTO) Set(val *CryptographicCapabilitiesDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptographicCapabilitiesDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptographicCapabilitiesDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptographicCapabilitiesDTO(val *CryptographicCapabilitiesDTO) *NullableCryptographicCapabilitiesDTO {
	return &NullableCryptographicCapabilitiesDTO{value: val, isSet: true}
}

func (v NullableCryptographicCapabilitiesDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptographicCapabilitiesDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


