/*
Candlepin

Candlepin is a subscription management server written in Java. It helps with management of software subscriptions.

API version: 4.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package caliri

import (
	"encoding/json"
)

// checks if the SetConsumerEnvironmentsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetConsumerEnvironmentsDTO{}

// SetConsumerEnvironmentsDTO struct for SetConsumerEnvironmentsDTO
type SetConsumerEnvironmentsDTO struct {
	ConsumerUuids []string `json:"consumerUuids,omitempty"`
	EnvironmentIds []string `json:"environmentIds,omitempty"`
}

// NewSetConsumerEnvironmentsDTO instantiates a new SetConsumerEnvironmentsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetConsumerEnvironmentsDTO() *SetConsumerEnvironmentsDTO {
	this := SetConsumerEnvironmentsDTO{}
	return &this
}

// NewSetConsumerEnvironmentsDTOWithDefaults instantiates a new SetConsumerEnvironmentsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetConsumerEnvironmentsDTOWithDefaults() *SetConsumerEnvironmentsDTO {
	this := SetConsumerEnvironmentsDTO{}
	return &this
}

// GetConsumerUuids returns the ConsumerUuids field value if set, zero value otherwise.
func (o *SetConsumerEnvironmentsDTO) GetConsumerUuids() []string {
	if o == nil || IsNil(o.ConsumerUuids) {
		var ret []string
		return ret
	}
	return o.ConsumerUuids
}

// GetConsumerUuidsOk returns a tuple with the ConsumerUuids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetConsumerEnvironmentsDTO) GetConsumerUuidsOk() ([]string, bool) {
	if o == nil || IsNil(o.ConsumerUuids) {
		return nil, false
	}
	return o.ConsumerUuids, true
}

// HasConsumerUuids returns a boolean if a field has been set.
func (o *SetConsumerEnvironmentsDTO) HasConsumerUuids() bool {
	if o != nil && !IsNil(o.ConsumerUuids) {
		return true
	}

	return false
}

// SetConsumerUuids gets a reference to the given []string and assigns it to the ConsumerUuids field.
func (o *SetConsumerEnvironmentsDTO) SetConsumerUuids(v []string) {
	o.ConsumerUuids = v
}

// GetEnvironmentIds returns the EnvironmentIds field value if set, zero value otherwise.
func (o *SetConsumerEnvironmentsDTO) GetEnvironmentIds() []string {
	if o == nil || IsNil(o.EnvironmentIds) {
		var ret []string
		return ret
	}
	return o.EnvironmentIds
}

// GetEnvironmentIdsOk returns a tuple with the EnvironmentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetConsumerEnvironmentsDTO) GetEnvironmentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.EnvironmentIds) {
		return nil, false
	}
	return o.EnvironmentIds, true
}

// HasEnvironmentIds returns a boolean if a field has been set.
func (o *SetConsumerEnvironmentsDTO) HasEnvironmentIds() bool {
	if o != nil && !IsNil(o.EnvironmentIds) {
		return true
	}

	return false
}

// SetEnvironmentIds gets a reference to the given []string and assigns it to the EnvironmentIds field.
func (o *SetConsumerEnvironmentsDTO) SetEnvironmentIds(v []string) {
	o.EnvironmentIds = v
}

func (o SetConsumerEnvironmentsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetConsumerEnvironmentsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConsumerUuids) {
		toSerialize["consumerUuids"] = o.ConsumerUuids
	}
	if !IsNil(o.EnvironmentIds) {
		toSerialize["environmentIds"] = o.EnvironmentIds
	}
	return toSerialize, nil
}

type NullableSetConsumerEnvironmentsDTO struct {
	value *SetConsumerEnvironmentsDTO
	isSet bool
}

func (v NullableSetConsumerEnvironmentsDTO) Get() *SetConsumerEnvironmentsDTO {
	return v.value
}

func (v *NullableSetConsumerEnvironmentsDTO) Set(val *SetConsumerEnvironmentsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableSetConsumerEnvironmentsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableSetConsumerEnvironmentsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetConsumerEnvironmentsDTO(val *SetConsumerEnvironmentsDTO) *NullableSetConsumerEnvironmentsDTO {
	return &NullableSetConsumerEnvironmentsDTO{value: val, isSet: true}
}

func (v NullableSetConsumerEnvironmentsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetConsumerEnvironmentsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


