/*
Candlepin

Candlepin is a subscription management server written in Java. It helps with management of software subscriptions.

API version: 4.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package caliri

import (
	"encoding/json"
)

// checks if the GetConsumer410Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConsumer410Response{}

// GetConsumer410Response struct for GetConsumer410Response
type GetConsumer410Response struct {
	DisplayMessage *string `json:"displayMessage,omitempty"`
	RequestUuid *string `json:"requestUuid,omitempty"`
	DeletedId *string `json:"deletedId,omitempty"`
}

// NewGetConsumer410Response instantiates a new GetConsumer410Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConsumer410Response() *GetConsumer410Response {
	this := GetConsumer410Response{}
	return &this
}

// NewGetConsumer410ResponseWithDefaults instantiates a new GetConsumer410Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConsumer410ResponseWithDefaults() *GetConsumer410Response {
	this := GetConsumer410Response{}
	return &this
}

// GetDisplayMessage returns the DisplayMessage field value if set, zero value otherwise.
func (o *GetConsumer410Response) GetDisplayMessage() string {
	if o == nil || IsNil(o.DisplayMessage) {
		var ret string
		return ret
	}
	return *o.DisplayMessage
}

// GetDisplayMessageOk returns a tuple with the DisplayMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConsumer410Response) GetDisplayMessageOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayMessage) {
		return nil, false
	}
	return o.DisplayMessage, true
}

// HasDisplayMessage returns a boolean if a field has been set.
func (o *GetConsumer410Response) HasDisplayMessage() bool {
	if o != nil && !IsNil(o.DisplayMessage) {
		return true
	}

	return false
}

// SetDisplayMessage gets a reference to the given string and assigns it to the DisplayMessage field.
func (o *GetConsumer410Response) SetDisplayMessage(v string) {
	o.DisplayMessage = &v
}

// GetRequestUuid returns the RequestUuid field value if set, zero value otherwise.
func (o *GetConsumer410Response) GetRequestUuid() string {
	if o == nil || IsNil(o.RequestUuid) {
		var ret string
		return ret
	}
	return *o.RequestUuid
}

// GetRequestUuidOk returns a tuple with the RequestUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConsumer410Response) GetRequestUuidOk() (*string, bool) {
	if o == nil || IsNil(o.RequestUuid) {
		return nil, false
	}
	return o.RequestUuid, true
}

// HasRequestUuid returns a boolean if a field has been set.
func (o *GetConsumer410Response) HasRequestUuid() bool {
	if o != nil && !IsNil(o.RequestUuid) {
		return true
	}

	return false
}

// SetRequestUuid gets a reference to the given string and assigns it to the RequestUuid field.
func (o *GetConsumer410Response) SetRequestUuid(v string) {
	o.RequestUuid = &v
}

// GetDeletedId returns the DeletedId field value if set, zero value otherwise.
func (o *GetConsumer410Response) GetDeletedId() string {
	if o == nil || IsNil(o.DeletedId) {
		var ret string
		return ret
	}
	return *o.DeletedId
}

// GetDeletedIdOk returns a tuple with the DeletedId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConsumer410Response) GetDeletedIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedId) {
		return nil, false
	}
	return o.DeletedId, true
}

// HasDeletedId returns a boolean if a field has been set.
func (o *GetConsumer410Response) HasDeletedId() bool {
	if o != nil && !IsNil(o.DeletedId) {
		return true
	}

	return false
}

// SetDeletedId gets a reference to the given string and assigns it to the DeletedId field.
func (o *GetConsumer410Response) SetDeletedId(v string) {
	o.DeletedId = &v
}

func (o GetConsumer410Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConsumer410Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayMessage) {
		toSerialize["displayMessage"] = o.DisplayMessage
	}
	if !IsNil(o.RequestUuid) {
		toSerialize["requestUuid"] = o.RequestUuid
	}
	if !IsNil(o.DeletedId) {
		toSerialize["deletedId"] = o.DeletedId
	}
	return toSerialize, nil
}

type NullableGetConsumer410Response struct {
	value *GetConsumer410Response
	isSet bool
}

func (v NullableGetConsumer410Response) Get() *GetConsumer410Response {
	return v.value
}

func (v *NullableGetConsumer410Response) Set(val *GetConsumer410Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConsumer410Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConsumer410Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConsumer410Response(val *GetConsumer410Response) *NullableGetConsumer410Response {
	return &NullableGetConsumer410Response{value: val, isSet: true}
}

func (v NullableGetConsumer410Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConsumer410Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


